version: "2.1"

networks:
  dc_network:
    driver: bridge

services:
  # ethereum test rpc network based on ganache-cli 
  dc_protocol:
    labels:
      - "TestRPC on port 1406"
      - "truffle ganache-cli"
    image:
      daocasino/protocol
    ports:
      - 1406:8545
    volumes:
      - ./protocol:/protocol
    networks:
       - dc_network
  
  # Bankroller node / casino backend
  # service watch dapp logic and reload node if his change 
  dc_bankroller:
    labels:
      - "dapp casino backend"
    depends_on:
      - dc_protocol
    image:
      daocasino/bankroller
    environment:
      - privateKey=0x8d5366123cb560bb606379f90a0bfd4769eecc0557f1b362dcae9012b548b1e5
    volumes:
      - ./protocol:/protocol
      - ./bankroller/dapps/:/bankroller/data_sdk/dapps/
    entrypoint: 
      ["sh", "./run_sdk_env.sh"]
    environment:
      - privateKey=0x8d5366123cb560bb606379f90a0bfd4769eecc0557f1b362dcae9012b548b1e5
    networks:
      - dc_network

