version: "2.1"

networks:
  dc_network:
    driver: bridge

services:
  # ethereum test rpc network based on ganache-cli 
  dc_protocol:
    container_name: dc_protocol
    labels:
      - "TestRPC on port 1406"
      - "truffle ganache-cli"
    image:
      daocasino/protocol
    ports:
      - 1406:8545
    volumes:
      - ./protocol:/protocol
    networks:
       - dc_network
  

  # Bankroller node / casino backend
  # service watch dapp logic and reload node if his change 
  dc_bankroller:
    container_name: dc_bankroller
    labels:
      - "dapp casino backend"
    depends_on:
      - dc_protocol
    image:
      daocasino/bankroller
    volumes:
      - ./protocol:/protocol
      - ./bankroller/dapps/:/bankroller/data_sdk/dapps/
      - ${DAPP_PATH}:/bankroller/data_sdk/dapps/sdk_dapp/
    entrypoint: 
      ["sh", "./run_${DC_NETWORK}_env.sh"]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - DAPP_ROOM=${DAPP_ROOM}
    networks:
      - dc_network


  dc_ipfs:
     image: ipfs/go-ipfs
     container_name: "ipfs_deployer"
     labels:
       - "IPFS node for Deploy DApp"
     # ports:
       # - 5002:5001
       # - 8181:8080
     volumes:
       - ${DAPP_PATH}:/go/target
